// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zBodyLogin = z.object({
    grant_type: z.union([
        z.string().regex(/password/),
        z.null()
    ]).optional(),
    username: z.string(),
    password: z.string(),
    scope: z.string().optional().default(''),
    client_id: z.union([
        z.string(),
        z.null()
    ]).optional(),
    client_secret: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zClienteCreate = z.object({
    nome: z.string(),
    email: z.string(),
    categoria: z.string(),
    endereco: z.string()
});

export const zClientePublic = z.object({
    nome: z.string(),
    email: z.string(),
    categoria: z.string(),
    endereco: z.string(),
    id: z.number().int()
});

export const zCompraCreate = z.object({
    data_compra: z.string().datetime(),
    valor: z.number(),
    categoria: z.string(),
    fornecedor_id: z.number().int()
});

export const zCompraPublic = z.object({
    data_compra: z.string().datetime(),
    valor: z.number(),
    categoria: z.string(),
    id: z.number().int(),
    fornecedor: z.object({
        nome: z.string().max(50),
        id: z.number().int()
    })
});

export const zFornecedorCreate = z.object({
    nome: z.string().max(50)
});

export const zFornecedorPublic = z.object({
    nome: z.string().max(50),
    id: z.number().int()
});

export const zHttpValidationError = z.object({
    detail: z.array(z.object({
        loc: z.array(z.unknown()),
        msg: z.string(),
        type: z.string()
    })).optional()
});

export const zItemCreate = z.object({
    preco_unitario: z.number(),
    quantidade: z.number().int(),
    produto_id: z.number().int()
});

export const zItemPublic = z.object({
    preco_unitario: z.number(),
    quantidade: z.number().int(),
    id: z.number().int(),
    produto: z.object({
        nome: z.string(),
        peso_em_gramas: z.number(),
        id: z.number().int()
    })
});

export const zProdutoCreate = z.object({
    nome: z.string(),
    peso_em_gramas: z.number()
});

export const zProdutoPublic = z.object({
    nome: z.string(),
    peso_em_gramas: z.number(),
    id: z.number().int()
});

export const zToken = z.object({
    access_token: z.string(),
    token_type: z.string().optional().default('bearer')
});

export const zUserPublic = z.object({
    email: z.string().email().max(255),
    is_active: z.boolean().optional().default(true),
    is_superuser: z.boolean().optional().default(false),
    full_name: z.union([
        z.string().max(255),
        z.null()
    ]).optional(),
    id: z.number().int()
});

export const zValidationError = z.object({
    loc: z.array(z.unknown()),
    msg: z.string(),
    type: z.string()
});

export const zVendaCreate = z.object({
    data_venda: z.string().datetime(),
    data_pagamento: z.union([
        z.string().datetime(),
        z.null()
    ]).optional(),
    cliente_id: z.number().int(),
    items: z.array(zItemCreate)
});

export const zVendaPublic = z.object({
    data_venda: z.string().datetime(),
    data_pagamento: z.union([
        z.string().datetime(),
        z.null()
    ]).optional(),
    id: z.number().int(),
    items: z.array(zItemPublic),
    cliente: zClientePublic
});

export const zReadClientesResponse = z.array(zClientePublic);

export const zCreateClienteResponse = zClientePublic;

export const zCountClientesResponse = z.number().int();

export const zDeleteClienteResponse = zClientePublic;

export const zReadClienteByIdResponse = zClientePublic;

export const zReadComprasResponse = z.array(zCompraPublic);

export const zCreateCompraResponse = zCompraPublic;

export const zCountComprasResponse = z.number().int();

export const zReadCompraByIdResponse = zCompraPublic;

export const zReadFornecedoresResponse = z.array(zFornecedorPublic);

export const zCreateFornecedorResponse = zFornecedorPublic;

export const zCountFornecedoresResponse = z.number().int();

export const zDeleteFornecedorResponse = zFornecedorPublic;

export const zReadFornecedorByIdResponse = zFornecedorPublic;

export const zReadProdutosResponse = z.array(zProdutoPublic);

export const zCreateProdutoResponse = zProdutoPublic;

export const zCountProdutosResponse = z.number().int();

export const zDeleteProdutoResponse = zProdutoPublic;

export const zReadProdutoByIdResponse = zProdutoPublic;

export const zReadVendasResponse = z.array(zVendaPublic);

export const zCreateVendaResponse = zVendaPublic;

export const zCountVendasResponse = z.number().int();

export const zReadVendaByIdResponse = zVendaPublic;

export const zLoginResponse = zToken;

export const zGetCurrentUserResponse = zUserPublic;